# http server
server:
  port: 8085
spring:
  #DataSource
  datasource:
    url: jdbc:mysql://localhost:3306/elearning?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  #JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop # tomcat
  thymeleaf:
    mode: HTML5 # html 5 mode
    cache: false # reload
    encoding: UTF-8 # encoding : utf 8
  h2:
    console:
      enabled: true
  data:
    elasticsearch:
      cluster-nodes: localhost:9300 #connection
      properties:
        transport:
          tcp:
            connect_timeout: 120s
# File upload config
file:
  server:
    url: http://localhost:8081/upload

# Elasticsearch server
elasticsearch:
  host: localhost
  port: 9300
  cluster:
    name: elearning